#! /bin/bash

spawn-job() {
    local max="$(cat /proc/cpuinfo | grep ^processor | wc -l)"
    local i=

    if [ "$1" = "-m" ]; then
        max="$2"
        shift 2
    fi
    test -n "$max" || exit 1

    while [ $# -gt 0 ]; do
       i=$max
       while [ $i -gt 0 ]; do
           test -n "$1" && $1 &
           shift
           i=$(($i-1))
       done

       for j in `jobs -p`; do
           wait $j
       done
   done
}
